@extends('layouts.medical-store')

@section('title', 'Bill Details')
@section('header', 'Bill #' . $bill->bill_id)
@section('subheader', 'Pharmacy Bill Details')

@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Bill Items</div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr><th>Description</th><th>Quantity</th><th>Unit Price</th><th>Amount</th></tr>
                    </thead>
                    <tbody>
                        @foreach($bill->items as $item)
                        <tr>
                            <td>{{ $item->item_description }}</div>
                            <td>{{ $item->quantity }} pcs</div>
                            <td>₱{{ number_format($item->unit_price, 2) }}</div>
                            <td>₱{{ number_format($item->amount, 2) }}</div>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3" class="text-end"><strong>Subtotal:</strong></div>
                            <td>₱{{ number_format($bill->total_amount, 2) }}</div>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-end"><strong>Discount:</strong></div>
                            <td>- ₱{{ number_format($bill->discount, 2) }}</div>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-end"><strong>Tax (12%):</strong></div>
                            <td>₱{{ number_format($bill->tax, 2) }}</div>
                        </tr>
                        <tr class="table-active">
                            <td colspan="3" class="text-end"><strong>Net Amount:</strong></div>
                            <td><strong>₱{{ number_format($bill->net_amount, 2) }}</strong></div>
                        </tr>
                    </tfoot>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">Bill Information</div>
            <div class="card-body">
                <p><strong>Patient:</strong> {{ $bill->patient->firstname ?? 'N/A' }} {{ $bill->patient->lastname ?? '' }}</p>
                <p><strong>Bill Date:</strong> {{ $bill->bill_date }}</p>
                <p><strong>Status:</strong> 
                    @if($bill->payment_status == 'paid')
                        <span class="badge bg-success">Paid</span>
                    @else
                        <span class="badge bg-warning">Pending</span>
                    @endif
                </p>
                <p><strong>Generated By:</strong> {{ $bill->generatedBy->firstname ?? 'N/A' }}</p>
                <hr>
                @if($bill->payment_status != 'paid')
                    <a href="{{ route('medical-store.billing.mark-paid', $bill->bill_id) }}" class="btn btn-success w-100" onclick="return confirm('Mark as paid?')">
                        Mark as Paid
                    </a>
                @endif
                <a href="{{ route('medical-store.billing.index') }}" class="btn btn-secondary w-100 mt-2">Back</a>
            </div>
        </div>
    </div>
</div>
@endsection