@extends('layouts.receptionist')

@section('title', 'Bill Details')
@section('header', 'Bill #' . $bill->bill_id)
@section('subheader', 'Patient: ' . ($bill->patient->firstname ?? 'N/A') . ' ' . ($bill->patient->lastname ?? ''))

@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Bill Items</div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr><th>Description</th><th>Quantity</th><th>Unit Price</th><th>Amount</th></tr>
                    </thead>
                    <tbody>
                        @foreach($bill->items as $item)
                        <tr>
                            <td>{{ $item->item_description }}</td>
                            <td>{{ $item->quantity }}</td>
                            <td>₱{{ number_format($item->unit_price, 2) }}</td>
                            <td>₱{{ number_format($item->amount, 2) }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr><td colspan="3" class="text-end"><strong>Subtotal:</strong></td>
                            <td>₱{{ number_format($bill->total_amount, 2) }}</td>
                        </tr>
                        <tr><td colspan="3" class="text-end"><strong>Discount:</strong></td>
                            <td>- ₱{{ number_format($bill->discount, 2) }}</td>
                        </tr>
                        <tr><td colspan="3" class="text-end"><strong>Tax (12%):</strong></td>
                            <td>₱{{ number_format($bill->tax, 2) }}</td>
                        </tr>
                        <tr class="table-active">
                            <td colspan="3" class="text-end"><strong>Net Amount:</strong></td>
                            <td><strong>₱{{ number_format($bill->net_amount, 2) }}</strong></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">Bill Information</div>
            <div class="card-body">
                <p><strong>Bill Date:</strong> {{ $bill->bill_date }}</p>
                <p><strong>Payment Status:</strong> 
                    <span class="badge bg-{{ $bill->payment_status == 'paid' ? 'success' : 'warning' }}">
                        {{ ucfirst($bill->payment_status) }}
                    </span>
                </p>
                <p><strong>Generated By:</strong> {{ $bill->generatedBy->firstname ?? 'N/A' }}</p>
                <hr>
                @if($bill->payment_status != 'paid')
                    <form action="{{ route('receptionist.billing.mark-paid', $bill->bill_id) }}" method="POST">
                        @csrf
                        <button type="submit" class="btn btn-success w-100" onclick="return confirm('Mark this bill as paid?')">
                            <i class="fas fa-check-circle"></i> Mark as Paid
                        </button>
                    </form>
                @endif
                <a href="{{ route('receptionist.billing.index') }}" class="btn btn-secondary w-100 mt-2">
                    <i class="fas fa-arrow-left"></i> Back
                </a>
            </div>
        </div>
    </div>
</div>
@endsection